### ISSUE TITLE
About ENCASE.

### ISSUE THREAD

**Issue by Joevaen** [cruzion/BachelorThesis#1]
Hi,
I saw you reproducethe base model of ENCASE by pytorch. You didn't use the other part of ENCASE algrithm, such as medical feature, right?

**Comment by cruzion** [comment]
Hi,
Yes, I have only reproduced the DNN part of ENCASE using Deep features.

**Comment by cruzion** [comment]
Hi, 
I think you could read the preprocess_physionet() function in util.py  to understand how it works and then after modifying, just run it.
Best,

**Comment by Joevaen** [comment]
> Hi,
> I think you could read the preprocess_physionet() function in util.py to understand how it works and then after modifying, just run it.
> Best,

Thanks a lot.
